verbose: false
instrumentation:
  root: .
  extensions:
    - .js
    - .jsx
  default-excludes: true
  excludes:
    - "**/*.spec.js"
    - "node_modules/**/*.*"
    - "dist/**/*.*"
  include-all-sources: true
reporting:
  reports:
    - lcov
